import { Colors } from '@constants/Colors';
import { StyleSheet } from 'react-native';

export const textStyles = StyleSheet.create({
    title: {
        fontFamily: 'Inter',
        fontWeight: '700',
        fontStyle: 'normal',
        fontSize: 28,
        lineHeight: 40,
        letterSpacing: 0,
        textAlign: 'center',
        textAlignVertical: 'center',
        color: Colors.light.black,
    },
    subtitle: {
        fontFamily: 'Inter',
        fontWeight: '600',
        fontSize: 18,
        lineHeight: 20,
        letterSpacing: 0,
        textAlignVertical: 'center',
    },
    body: {
        fontFamily: 'Inter',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: 14,
        lineHeight: 21,
        letterSpacing: 0,
        textAlign: 'center',
    },
    button: {
        fontFamily: 'Inter',
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: 16,
        lineHeight: 24,
        letterSpacing: 0,
        textAlignVertical: 'center',
    },
    text: {
        fontFamily: 'Inter',
        fontWeight: '400',
        fontStyle: 'normal',
        fontSize: 14,
        lineHeight: 21,
        letterSpacing: 0,
        textAlignVertical: 'center',
        textAlign: 'left',
    },
    mini: {
        fontFamily: 'Inter',
        fontWeight: '500',
        fontStyle: 'normal',
        fontSize: 12,
        lineHeight: 18,
        letterSpacing: 0,
        textAlignVertical: 'center',
        textAlign: 'justify',
    },
    label: {
        fontSize: 14,
        marginBottom: 5,
        color: '#333',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        marginBottom: 15,
        fontSize: 16,
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
});
